site_name: OSG Documentation
site_url: https://opensciencegrid.github.io/docs
repo_url: https://github.com/opensciencegrid/docs
theme: readthedocs

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- Installation Overview: 'install-overview.md'
- Install Guides - Common:
  - 'CA Certificates': 'common/ca.md'
  - 'Yum Repos': 'common/yum.md'
- Install Guides - Client:
  - 'CVMFS': 'client/cvmfs.md'
  - 'Worker Node (RPM install)': 'client/wn.md'
  - 'Worker Node (tarball install)': 'client/wn-tarball.md'
  - 'Worker Node (OASIS install)': 'client/wn-oasis.md'
- Install Guides - Compute:
  - 'HTCondor-CE': 'compute-element/install-htcondor-ce.md'
- Install Guides - Data:
  - 'GridFTP Server': 'data/gridftp.md'
  - 'HTTP Cache': 'data/frontier-squid.md'
- Install Guides - Monitoring:
  - 'RSV': 'monitoring/rsv.md'
  - 'RSV GlideinWMS Tester': 'monitoring/rsv-gwms-tester.md'
- Install Guides - Other:
  - 'GSI-enabled SSH': 'other/gsissh.md'
  - 'LCMAPS-VOMS authentication': 'security/lcmaps-voms-authentication.md'
- Overviews:
  - 'HTCondor-CE': 'compute-element/htcondor-ce-overview.md'
- Release Information:
  - 'OSG Release Series': 'release/release_series.md'
  - 'Supported Platforms': 'release/supported_platforms.md'
  - 'Yum Basics': 'release/yum-basics.md'
  - 'RPM Signing': 'release/signing.md'
- Usage Guides:
  - 'Certificate Tools': 'common/pki-cli.md'
  - 'Configuration with OSG-Configure': 'other/configuration-with-osg-configure.md'
  - 'Worker Node Environment': 'client/using-wn.md'
- In-Progress Docs:
  - 'CA Updater': 'common/ca_updater.md'
  - 'Certificate Request Scripts': 'common/cert_scripts.md'
  - 'Job Router Recipe': 'compute-element/job_router.md'
- Deprecated Software:
  - 'BeStMan Overview': 'data/bestman-overview.md'
  - 'BeStMan Install': 'data/bestman-install.md'
  - 'Worker node glexec Install': 'client/glexec.md'
- 'Get Help': 'common/help.md'

markdown_extensions:
  - admonition
  - codehilite
  - osg_markdown.colors

