site_name: OSG Documentation
site_url: https://opensciencegrid.github.io/docs/
repo_url: https://github.com/opensciencegrid/docs/
google_analytics: ['UA-69012-29', 'opensciencegrid.github.io']
theme:
  name: material
  custom_dir: osgthedocs
  favicon: 'img/favicon.ico'

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- Site Planning: 'site-planning.md'
- Compute Element:
  - 'HTCondor-CE Overview': 'compute-element/htcondor-ce-overview.md'
  - 'Request a Hosted CE': 'compute-element/hosted-ce.md'
  - 'Install HTCondor-CE': 'compute-element/install-htcondor-ce.md'
  - 'Job Router Recipes': 'compute-element/job-router-recipes.md'
  - 'Troubleshooting HTCondor-CE': 'compute-element/troubleshoot-htcondor-ce.md'
  - 'Submitting to HTCondor-CE': 'compute-element/submit-htcondor-ce.md'
- Worker Node:
  - 'Overview': 'worker-node/using-wn.md'
  - 'Install from RPM': 'worker-node/install-wn.md'
  - 'Install from Tarball': 'worker-node/install-wn-tarball.md'
  - 'Install from OASIS': 'worker-node/install-wn-oasis.md'
  - 'Install CVMFS': 'worker-node/install-cvmfs.md'
  - 'Install Singularity': 'worker-node/install-singularity.md'
  - 'Using WN Containers': 'worker-node/using-wn-containers.md'
- Data:
  - HTTP & CVMFS:
    - 'Install Squid HTTP Cache': 'data/frontier-squid.md'
    - 'Update OASIS Shared Repo': 'data/update-oasis.md'
    - 'Install an OASIS Repo': 'data/external-oasis-repos.md'
  - POSIX Storage:
    - 'Install GridFTP Server': 'data/gridftp.md'
    - 'Install Load Balanced GridFTP': 'data/load-balanced-gridftp.md'
  - XRootD:
    - 'XRootD Overview': 'data/xrootd/overview.md'
    - 'Install XRootD Standalone': 'data/xrootd/install-standalone.md'
    - 'Install XRootD SE': 'data/xrootd/install-storage-element.md'
    - 'Configure Authorization': 'data/xrootd/xrootd-authorization.md'
    - 'Using XRootD': 'data/xrootd/install-client.md'
  - StashCache:
    - 'StashCache Overview': 'data/stashcache/overview.md'
    - 'Install StashCache Cache': 'data/stashcache/install-cache.md'
    - 'Install StashCache Origin': 'data/stashcache/install-origin.md'
    - 'Getting VO data into StashCache': 'data/stashcache/vo-data.md'
  - HDFS:
    - 'HDFS Overview': 'data/hadoop-overview.md'
    - 'Install HDFS': 'data/install-hadoop.md'
- Security:
  - 'LCMAPS VOMS authentication': 'security/lcmaps-voms-authentication.md'
  - 'Host Certificates': 'security/host-certs.md'
  - 'User Certificates': 'security/user-certs.md'
  - 'Certificate Management Reference': 'security/certificate-management.md'
- Common:
  - 'CA Certificates': 'common/ca.md'
  - 'Yum Repos': 'common/yum.md'
  - 'Configuration with OSG-Configure': 'other/configuration-with-osg-configure.md'
  - 'Registration': 'common/registration.md'
- Other:
  - 'Install GSI-enabled SSH': 'other/gsissh.md'
  - 'Install GlideinWMS Frontend': 'other/install-gwms-frontend.md'
  - 'Install a CVMFS Stratum 1': 'other/install-cvmfs-stratum1.md'
  - 'Install the Network Performance Toolkit': 'other/network-performance-toolkit.md'
  - 'Troubleshooting Gratia': 'other/troubleshooting-gratia.md'
  - 'Install Transfer Log Filebeats': 'other/schedd-filebeats.md'
- Release Information:
  - 'Release Note Overview': 'release/notes.md'
  - 3.4 Release Notes:
    - 'OSG Release 3.4.23': 'release/3.4/release-3-4-23.md'
    - 'OSG Release 3.4.22-2': 'release/3.4/release-3-4-22-2.md'
    - 'OSG Release 3.4.22': 'release/3.4/release-3-4-22.md'
    - 'OSG Release 3.4.21': 'release/3.4/release-3-4-21.md'
    - 'OSG Release 3.4.20': 'release/3.4/release-3-4-20.md'
    - 'OSG Release 3.4.19': 'release/3.4/release-3-4-19.md'
    - 'OSG Release 3.4.18-2': 'release/3.4/release-3-4-18-2.md'
    - 'OSG Release 3.4.18': 'release/3.4/release-3-4-18.md'
    - 'OSG Release 3.4.17-3': 'release/3.4/release-3-4-17-3.md'
    - 'OSG Release 3.4.17-2': 'release/3.4/release-3-4-17-2.md'
    - 'OSG Release 3.4.17': 'release/3.4/release-3-4-17.md'
    - 'OSG Release 3.4.16-2': 'release/3.4/release-3-4-16-2.md'
    - 'OSG Release 3.4.16': 'release/3.4/release-3-4-16.md'
    - 'OSG Release 3.4.15': 'release/3.4/release-3-4-15.md'
    - 'OSG Release 3.4.14-2': 'release/3.4/release-3-4-14-2.md'
    - 'OSG Release 3.4.14': 'release/3.4/release-3-4-14.md'
    - 'OSG Release 3.4.13': 'release/3.4/release-3-4-13.md'
    - 'OSG Release 3.4.12-3': 'release/3.4/release-3-4-12-3.md'
    - 'OSG Release 3.4.12-2': 'release/3.4/release-3-4-12-2.md'
    - 'OSG Release 3.4.12': 'release/3.4/release-3-4-12.md'
    - 'OSG Release 3.4.11': 'release/3.4/release-3-4-11.md'
    - 'OSG Release 3.4.10': 'release/3.4/release-3-4-10.md'
    - 'OSG Release 3.4.9-2': 'release/3.4/release-3-4-9-2.md'
    - 'OSG Release 3.4.9': 'release/3.4/release-3-4-9.md'
    - 'OSG Release 3.4.8': 'release/3.4/release-3-4-8.md'
    - 'OSG Release 3.4.7': 'release/3.4/release-3-4-7.md'
    - 'OSG Release 3.4.6-2': 'release/3.4/release-3-4-6-2.md'
    - 'OSG Release 3.4.6': 'release/3.4/release-3-4-6.md'
    - 'OSG Release 3.4.5-4': 'release/3.4/release-3-4-5-4.md'
    - 'OSG Release 3.4.5-3': 'release/3.4/release-3-4-5-3.md'
    - 'OSG Release 3.4.5-2': 'release/3.4/release-3-4-5-2.md'
    - 'OSG Release 3.4.5': 'release/3.4/release-3-4-5.md'
    - 'OSG Release 3.4.4-3': 'release/3.4/release-3-4-4-3.md'
    - 'OSG Release 3.4.4-2': 'release/3.4/release-3-4-4-2.md'
    - 'OSG Release 3.4.4': 'release/3.4/release-3-4-4.md'
    - 'OSG Release 3.4.3': 'release/3.4/release-3-4-3.md'
    - 'OSG Release 3.4.2-2': 'release/3.4/release-3-4-2-2.md'
    - 'OSG Release 3.4.2': 'release/3.4/release-3-4-2.md'
    - 'OSG Release 3.4.1-2': 'release/3.4/release-3-4-1-2.md'
    - 'OSG Release 3.4.1': 'release/3.4/release-3-4-1.md'
    - 'OSG Release 3.4.0-2': 'release/3.4/release-3-4-0-2.md'
    - 'OSG Release 3.4.0': 'release/3.4/release-3-4-0.md'
  - 'OSG Release Series': 'release/release_series.md'
  - 'Supported Platforms': 'release/supported_platforms.md'
  - 'OSG upcoming software': 'other/install-osg-upcoming-software.md'
  - 'Yum Basics': 'release/yum-basics.md'
  - 'RPM Signing': 'release/signing.md'
  - 'Contrib Software': 'release/contrib.md'
- Monitoring:
  - 'Install RSV': 'monitoring/install-rsv.md'
  - 'Advanced RSV Configuration': 'monitoring/advanced-rsv-configuration.md'
  - 'Manage RSV via rsv-control': 'monitoring/rsv-control.md'
  - 'RSV GlideinWMS Tester': 'monitoring/install-rsv-gwms-tester.md'
- 'Get Help': 'common/help.md'

markdown_extensions:
  - admonition
  - codehilite
  - toc:
     permalink: True
  - osg_markdown.colors
