site_name: OSG Site Documentation
site_url: https://osg-htc.org/docs/
repo_url: https://github.com/osg-htc/docs/
extra:
  analytics:
    provider: google
    property: UA-69012-29
theme:
  name: material
  custom_dir: osgthedocs
  favicon: 'img/favicon.ico'
  features:
    - navigation.sections
    - navigation.top

extra_css:
  - css/extra.css

nav:
- Home: 'index.md'
- Site Planning: 'site-planning.md'
- Site Verification: 'site-verification.md'
- Site Maintenance: 'site-maintenance.md'
- 'Help / Security Incidents': 'common/help.md'
- Registration:
  - Contact Information: 'common/contact-registration.md'
  - Resources and Collaborations: 'common/registration.md'
- Resource Sharing:
  - Compute:
    - 'Overview': 'resource-sharing/overview.md'
    - Pilot Containers:
      - 'Site Backfill': 'resource-sharing/os-backfill-containers.md'
      - 'User Allocations': 'resource-sharing/user-containers.md'
    - Compute Entrypoint:
      - 'HTCondor-CE Overview': 'compute-element/htcondor-ce-overview.md'
      - 'Request a Hosted CE': 'compute-element/hosted-ce.md'
      - 'Install HTCondor-CE': 'compute-element/install-htcondor-ce.md'
    - Worker Node:
        - 'Overview': 'worker-node/using-wn.md'
        - 'Install from RPM': 'worker-node/install-wn.md'
        - 'Install from Tarball': 'worker-node/install-wn-tarball.md'
        - 'Install from OASIS': 'worker-node/install-wn-oasis.md'
        - 'Install CVMFS': 'worker-node/install-cvmfs.md'
        - 'Install Apptainer': 'worker-node/install-apptainer.md'
        - 'Using WN Containers': 'worker-node/using-wn-containers.md'
  - Data:
    - HTTP & OASIS:
      - 'Running Frontier Squid in a Container': 'data/run-frontier-squid-container.md'
      - 'Install Frontier Squid RPM': 'data/frontier-squid.md'
      - 'Update OASIS Shared Repo': 'data/update-oasis.md'
      - 'Install an OASIS Repo': 'data/external-oasis-repos.md'
    - XRootD:
      - 'XRootD Overview': 'data/xrootd/overview.md'
      - 'Install XRootD Standalone': 'data/xrootd/install-standalone.md'
      - 'Configure Authorization': 'data/xrootd/xrootd-authorization.md'
      - 'Using XRootD': 'data/xrootd/install-client.md'
      - 'Install CMS XCache': 'data/xrootd/install-cms-xcache.md'
      - 'Install XRootD Shoveler': 'data/xrootd/install-shoveler.md'
  - Other:
    - 'Configuration with OSG-Configure': 'other/configuration-with-osg-configure.md'
    - 'Install GlideinWMS Frontend': 'other/install-gwms-frontend.md'
    - 'Install a CVMFS Stratum 1': 'other/install-cvmfs-stratum1.md'
    - 'Troubleshooting Gratia': 'other/troubleshooting-gratia.md'
    - 'Install Transfer Log Filebeats': 'other/schedd-filebeats.md'
    - 'Install OSG Token Renewal Service': 'other/osg-token-renewer.md'
- Access Point:
  - 'Install an OSPool Access Point': 'submit/install-ospool-ap.md'
  - 'Acceptable Use Policy': 'submit/ap-ospool-aup.md'
- 'Data Federation (OSDF)':
  - 'Overview': 'data/stashcache/overview.md'
  - Data Cache:
      - 'Install from container': 'data/stashcache/run-stashcache-container.md'
      - 'Install from RPM': 'data/stashcache/install-cache.md'
  - Data Origin:
      - 'Install from container': 'data/stashcache/run-stash-origin-container.md'
      - 'Install from RPM': 'data/stashcache/install-origin.md'
      - 'Publishing VO data': 'data/stashcache/vo-data.md'
- Releases:
  - 'Release Series': 'release/release_series.md'
  - OSG 23:
     - 'News': 'release/osg-23.md'
     - 'Updating to OSG 23': 'release/updating-to-osg-23.md'
  - OSG 3.6:
     - 'News': 'release/osg-36.md'
     - 'Updating to OSG 3.6': 'release/updating-to-osg-36.md'
  - 'Supported Platforms': 'release/supported_platforms.md'
  - 'OSG Yum Repos': 'common/yum.md'
  - 'Yum Basics': 'release/yum-basics.md'
  - 'RPM Signing': 'release/signing.md'
- Tokens:
  - Overview: 'security/tokens/overview.md'
  - Using Tokens: 'security/tokens/using-tokens.md'
- CA Certificates:
  - 'Overview': 'common/ca.md'
  - 'Certificate Management Reference': 'security/certificate-management.md'
  - 'Host Certificates':
    - 'Overview': 'security/host-certs/overview.md'
    - 'Using InCommon': 'security/host-certs/incommon.md'
    - "Using Let's Encrypt": 'security/host-certs/lets-encrypt.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - meta
  - toc:
      permalink: True
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list

plugins:
  - search
  - redirects:
      redirect_maps:
        site-responsibilities.md: site-maintenance.md
        submit/osg-flock.md: submit/install-ospool-ap.md

